name: hello_audio_stream
description: Audio stream cache client using WebSocket
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  web_socket_channel: ^3.0.2
  shelf: ^1.4.0
  shelf_web_socket: ^3.0.0
  args: ^2.6.0
  crypto: ^3.0.6
  intl: ^0.20.2
  async: ^2.12.0

  logging: any
dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
